name: smart_qr_scanner_example
description: Example app demonstrating smart_qr_scanner package features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smart_qr_scanner:
    path: ../
  qr: ^3.0.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  shared_preferences: ^2.3.0
  path_provider: ^2.1.0
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  camera_android_camerax: 0.6.5

flutter:
  uses-material-design: true
