include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - eol_at_end_of_file
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - unnecessary_string_interpolations
    - use_key_in_widget_constructors
